### ISSUE TITLE
 Error: sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= integrity checksum failed when using sha1: wanted sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= but got sha512-

### ISSUE THREAD

**Issue by starplatinum3** [caoyu48/vue-g6-editor#60]
npm i 的时候
文档：Dprojvueeditorvue-g6-editornpm insta...
链接：http://note.youdao.com/noteshare?id=1df42113544224ded2fa363b9d28b364&sub=BD9206DB64134561ACF6F41ED72B90DA

D:\proj\vue\editor\vue-g6-editor>npm install --save @antv/g6
npm ERR! code EINTEGRITY
npm ERR! sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= integrity checksum failed when using sha1: wanted sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= but got sha512-mwq
eW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA== sha1-stEE/g2Psnz54KHNqCYt04M8bKs=. (5537 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\npm\cache\_logs\2023-01-20T11_26_48_127Z-debug.log
...

ract string-width@3.1.0 extracted to D:\proj\vue\editor\vue-g6-editor\node_modules\.staging\string-width-d7c0f901 (141ms)
12412 silly extract wrap-ansi@5.1.0 extracted to D:\proj\vue\editor\vue-g6-editor\node_modules\.staging\wrap-ansi-2bf1172f (141ms)
12413 silly extract websocket-extensions@0.1.3
12414 silly tarball trying websocket-driver@0.7.3 by hash: sha1-otTg1PTxFvHmKX66WLBdQwEA6fk=
12415 silly tarball trying websocket-extensions@0.1.3 by hash: sha1-XS/yKXcAPsaHpLhwc9+7rBRszyk=
12416 http fetch GET 200 https://cdn.npmmirror.com/packages/webpack-dev-server/3.8.0/webpack-dev-server-3.8.0.tgz 879ms
12417 verbose stack Error: sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= integrity checksum failed when using sha1: wanted sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= but got sha512-mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA== sha1-stEE/g2Psnz54KHNqCYt04M8bKs=. (5537 bytes)
12417 verbose stack     at Transform.<anonymous> (D:\env\node14\node-v14.19.3-win-x64\node_modules\npm\node_modules\ssri\index.js:328:19)
12417 verbose stack     at Transform.emit (events.js:412:35)
12417 verbose stack     at endReadableNT (internal/streams/readable.js:1333:12)
12417 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
12418 verbose cwd D:\proj\vue\editor\vue-g6-editor
12419 verbose Windows_NT 10.0.22000
12420 verbose argv "D:\\env\\node14\\node-v14.19.3-win-x64\\node.exe" "D:\\env\\node14\\node-v14.19.3-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@antv/g6"
12421 verbose node v14.19.3
12422 verbose npm  v6.14.17
12423 error code EINTEGRITY
12424 error sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= integrity checksum failed when using sha1: wanted sha1-60MZjF4vuDuTI6vuY72Hg2+afIU= but got sha512-mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA== sha1-stEE/g2Psnz54KHNqCYt04M8bKs=. (5537 bytes)
12425 verbose exit [ 1, true ]

**Comment by myzonehome** [comment]
删除package-lock.json文件在npm i
